- header:
    model: mqm9700
    nvue-api-version: nvue_v1
    rev-id: 1.0
    version: 25.01.3932-014
- set:
    interface:
      eth0:
        description: PORTI1
        type: eth
      ib0:
        ip:
          address:
            2.2.2.11/24: {}
        type: ipoib
      sw2p1:
        link:
          mtu: 1024
      sw2p1,sw32p1:
        link:
          ib-speed: hdr
      sw2p1,sw32p1,sw3p2:
        type: ib
      sw3p2:
        link:
          state:
            down: {}
    system:
      aaa:
        authentication:
          failthrough: enabled
          order: radius,local
        ldap:
          base-dn: dc=itzgeek,dc=local
          bind-dn: cn=ldapadm,dc=itzgeek,dc=local
          hostname:
            10.237.0.86: {}
          secret: secret
        radius:
          auth-type: chap
          hostname:
            10.7.1.131: {}
            fdfd:fdfd:7:3:250:56ff:febe:7c22:
              priority: 2
          secret: testing123
        tacacs:
          hostname:
            10.7.1.130: {}
            fdfd:fdfd:10:237:250:56ff:fe1b:56:
              priority: 2
          secret: testing123
        user:
          alon:
            password: $y$j9T$pUsDr8V55akJ6WgfjVvze.$gperjLnCy0onUXxsu4h5lwy2ZlxryUBWV56eK21lTxD
          mon:
            password: $y$j9T$CuAnwwjJMXYIBFVuJ7KN51$nPz./46jyFVBzuySd02vaS/DriCgfiC2PrdCKLKH.o2
            role: monitor
      message:
        post-login: yoavpost
        pre-login: yoavpre123
      ntp:
        server:
          192.168.1.2:
            state: enabled
      security:
        password-hardening:
          state: enabled
      snmp-server:
        auto-refresh-interval: 5
        listening-address:
          all: {}
        readonly-community:
          '12345678': {}
        state: enabled
        system-contact: jemmyf
        system-location: MTL1
      ssh-server:
        authentication-retries: 55
        login-timeout: 555
        max-sessions: 3
      syslog:
        server:
          10.7.49.202:
            protocol: tcp
          192.168.1.2: {}
